/**
 * profilsDPEOfficiels.ts — Comptes de TOUS les profils de l'organigramme officiel DPE
 * (Note de Direction N°005/2023). Généré automatiquement. Mot de passe : dpe2026.
 * Chaque profil porte direction + département/cellule + poste → visibilité calculée (ABAC).
 */
import type { TestUser } from './authStore';

export const PROFILS_DPE_OFFICIELS: TestUser[] = [
 {
  "id": "p_0",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "directeur.principal.equipement@dpe.sn",
  "password": "dpe2026",
  "role": "DIR_DPE",
  "direction": "EM_DPE",
  "poste": "Directeur Principal Équipement",
  "initials": "AB",
  "avatarColor": "#3D1A6B"
 },
 {
  "id": "p_1",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "conseiller.technique.dpe@dpe.sn",
  "password": "dpe2026",
  "role": "EXPERT",
  "direction": "EM_DPE",
  "poste": "Conseiller Technique DPE",
  "initials": "FS",
  "avatarColor": "#7C3AED"
 },
 {
  "id": "p_2",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "chef.de.cellule.suivi.evaluation@dpe.sn",
  "password": "dpe2026",
  "role": "PMO",
  "direction": "CSE",
  "poste": "Chef de Cellule Suivi-Évaluation",
  "initials": "OD",
  "avatarColor": "#7C3AED",
  "cellule": "CSE"
 },
 {
  "id": "p_3",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "expert.gestion.de.projet.cse@dpe.sn",
  "password": "dpe2026",
  "role": "EXPERT",
  "direction": "CSE",
  "poste": "Expert Gestion de Projet / CSE",
  "initials": "AN",
  "avatarColor": "#7C3AED",
  "cellule": "CSE"
 },
 {
  "id": "p_4",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "assistant.gestion.de.projet.cse@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "CSE",
  "poste": "Assistant Gestion de Projet / CSE",
  "initials": "MF",
  "avatarColor": "#4B5563",
  "cellule": "CSE"
 },
 {
  "id": "p_5",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "responsable.suivi.evaluation.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DEP",
  "poste": "Responsable Suivi-Évaluation DEP",
  "initials": "MS",
  "avatarColor": "#059669"
 },
 {
  "id": "p_6",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "responsable.suivi.evaluation.der@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DER",
  "poste": "Responsable Suivi-Évaluation DER",
  "initials": "CS",
  "avatarColor": "#059669"
 },
 {
  "id": "p_7",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "responsable.suivi.evaluation.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DGC",
  "poste": "Responsable Suivi-Évaluation DGC",
  "initials": "AG",
  "avatarColor": "#059669"
 },
 {
  "id": "p_8",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "responsable.suivi.evaluation.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DIT",
  "poste": "Responsable Suivi-Évaluation DIT",
  "initials": "ID",
  "avatarColor": "#059669"
 },
 {
  "id": "p_9",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "responsable.suivi.evaluation.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPBM_UE",
  "poste": "Responsable Suivi-Évaluation CPBM_UE",
  "initials": "KC",
  "avatarColor": "#059669",
  "cellule": "CSE"
 },
 {
  "id": "p_10",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "responsable.suivi.evaluation.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CC26",
  "poste": "Responsable Suivi-Évaluation CC26",
  "initials": "MS",
  "avatarColor": "#059669",
  "cellule": "CSE"
 },
 {
  "id": "p_11",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "responsable.suivi.evaluation.cpamacel.ee@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPAMACEL_EE",
  "poste": "Responsable Suivi-Évaluation CPAMACEL_EE",
  "initials": "BK",
  "avatarColor": "#059669",
  "cellule": "CSE"
 },
 {
  "id": "p_12",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "responsable.suivi.evaluation.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Responsable Suivi-Évaluation CPADERAU",
  "initials": "SM",
  "avatarColor": "#059669",
  "cellule": "CSE"
 },
 {
  "id": "p_13",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "coordonnateur.administration.budget@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "EM_DPE",
  "poste": "Coordonnateur Administration & Budget",
  "initials": "NT",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_14",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "assistante.de.direction.cab@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "EM_DPE",
  "poste": "Assistante de Direction / CAB",
  "initials": "AS",
  "avatarColor": "#4B5563"
 },
 {
  "id": "p_15",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "chauffeur.dpe@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "EM_DPE",
  "poste": "Chauffeur DPE",
  "initials": "CF",
  "avatarColor": "#0891B2"
 },
 {
  "id": "p_16",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "directeur.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DEP",
  "poste": "Directeur DEP",
  "initials": "PG",
  "avatarColor": "#0F766E"
 },
 {
  "id": "p_17",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "expert.suivi.evaluation.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DEP",
  "poste": "Expert Suivi-Évaluation DEP",
  "initials": "SW",
  "avatarColor": "#059669"
 },
 {
  "id": "p_18",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "animateur.qhse.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DEP",
  "poste": "Animateur QHSE / DEP",
  "initials": "BD",
  "avatarColor": "#059669"
 },
 {
  "id": "p_19",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "assistante.de.direction.dep@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DEP",
  "poste": "Assistante de Direction / DEP",
  "initials": "RN",
  "avatarColor": "#4B5563"
 },
 {
  "id": "p_20",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "chef.uagl.dep@dpe.sn",
  "password": "dpe2026",
  "role": "RESP_LOG",
  "direction": "DEP",
  "poste": "Chef UAGL / DEP",
  "initials": "AB",
  "avatarColor": "#0E7490"
 },
 {
  "id": "p_21",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "assistant.administratif.budget.uagl.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DEP",
  "poste": "Assistant Administratif Budget / UAGL DEP",
  "initials": "FS",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_22",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "chef.groupe.logistique.dep@dpe.sn",
  "password": "dpe2026",
  "role": "RESP_LOG",
  "direction": "DEP",
  "poste": "Chef Groupe Logistique / DEP",
  "initials": "OD",
  "avatarColor": "#0E7490"
 },
 {
  "id": "p_23",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "chauffeur.uagl.dep@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "DEP",
  "poste": "Chauffeur / UAGL DEP",
  "initials": "AN",
  "avatarColor": "#0891B2"
 },
 {
  "id": "p_24",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "chef.de.departement.energies.conventionnelles@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DEP",
  "poste": "Chef de Département Énergies Conventionnelles",
  "initials": "MF",
  "avatarColor": "#0F766E",
  "departement": "DEP_PEC"
 },
 {
  "id": "p_25",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "chef.de.projet.energies.conventionnelles@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DEP",
  "poste": "Chef de Projet Énergies Conventionnelles",
  "initials": "MS",
  "avatarColor": "#1D4ED8",
  "departement": "DEP_PEC"
 },
 {
  "id": "p_26",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "ingenieur.d.etudes.energies.conventionnelles@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DEP",
  "poste": "Ingénieur d'Études Énergies Conventionnelles",
  "initials": "CS",
  "avatarColor": "#2563EB",
  "departement": "DEP_PEC"
 },
 {
  "id": "p_27",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "controleur.energies.conventionnelles@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR",
  "direction": "DEP",
  "poste": "Contrôleur Énergies Conventionnelles",
  "initials": "AG",
  "avatarColor": "#D97706",
  "departement": "DEP_PEC"
 },
 {
  "id": "p_28",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "assistant.projet.energies.conventionnelles@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DEP",
  "poste": "Assistant Projet Énergies Conventionnelles",
  "initials": "ID",
  "avatarColor": "#4B5563",
  "departement": "DEP_PEC"
 },
 {
  "id": "p_29",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "chef.de.departement.energies.renouvelables@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DEP",
  "poste": "Chef de Département Énergies Renouvelables",
  "initials": "KC",
  "avatarColor": "#0F766E",
  "departement": "DEP_PER"
 },
 {
  "id": "p_30",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "chef.de.projet.energies.renouvelables@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DEP",
  "poste": "Chef de Projet Énergies Renouvelables",
  "initials": "MS",
  "avatarColor": "#1D4ED8",
  "departement": "DEP_PER"
 },
 {
  "id": "p_31",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "ingenieur.d.etudes.energies.renouvelables@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DEP",
  "poste": "Ingénieur d'Études Énergies Renouvelables",
  "initials": "BK",
  "avatarColor": "#2563EB",
  "departement": "DEP_PER"
 },
 {
  "id": "p_32",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "controleur.energies.renouvelables@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR",
  "direction": "DEP",
  "poste": "Contrôleur Énergies Renouvelables",
  "initials": "SM",
  "avatarColor": "#D97706",
  "departement": "DEP_PER"
 },
 {
  "id": "p_33",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "assistant.projet.energies.renouvelables@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DEP",
  "poste": "Assistant Projet Énergies Renouvelables",
  "initials": "NT",
  "avatarColor": "#4B5563",
  "departement": "DEP_PER"
 },
 {
  "id": "p_34",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "directeur.der@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DER",
  "poste": "Directeur DER",
  "initials": "AS",
  "avatarColor": "#0F766E"
 },
 {
  "id": "p_35",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "expert.suivi.evaluation.der@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DER",
  "poste": "Expert Suivi-Évaluation DER",
  "initials": "CF",
  "avatarColor": "#059669"
 },
 {
  "id": "p_36",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "responsable.administratif.financier.der@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DER",
  "poste": "Responsable Administratif & Financier / DER",
  "initials": "PG",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_37",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "assistante.de.direction.der@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DER",
  "poste": "Assistante de Direction / DER",
  "initials": "SW",
  "avatarColor": "#4B5563"
 },
 {
  "id": "p_38",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "animateur.qhse.der@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DER",
  "poste": "Animateur QHSE / DER",
  "initials": "BD",
  "avatarColor": "#059669"
 },
 {
  "id": "p_39",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "chef.de.departement.projets.transport@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DER",
  "poste": "Chef de Département Projets Transport",
  "initials": "RN",
  "avatarColor": "#0F766E",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_40",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "assistante.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DER",
  "poste": "Assistante / DPT",
  "initials": "AB",
  "avatarColor": "#4B5563",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_41",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "chef.de.projet.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DER",
  "poste": "Chef de Projet / DPT",
  "initials": "FS",
  "avatarColor": "#1D4ED8",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_42",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "ingenieur.d.etudes.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DER",
  "poste": "Ingénieur d'Études / DPT",
  "initials": "OD",
  "avatarColor": "#2563EB",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_43",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "controleur.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR",
  "direction": "DER",
  "poste": "Contrôleur / DPT",
  "initials": "AN",
  "avatarColor": "#D97706",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_44",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "assistant.projet.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DER",
  "poste": "Assistant Projet / DPT",
  "initials": "MF",
  "avatarColor": "#4B5563",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_45",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "cartographe.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DER",
  "poste": "Cartographe / DPT",
  "initials": "MS",
  "avatarColor": "#2563EB",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_46",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "assistant.administratif.budget.uagl.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DER",
  "poste": "Assistant Administratif Budget / UAGL DPT",
  "initials": "CS",
  "avatarColor": "#B45309",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_47",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "chef.groupe.logistique.uagl.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "RESP_LOG",
  "direction": "DER",
  "poste": "Chef Groupe Logistique / UAGL DPT",
  "initials": "AG",
  "avatarColor": "#0E7490",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_48",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "chauffeur.uagl.dpt@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "DER",
  "poste": "Chauffeur / UAGL DPT",
  "initials": "ID",
  "avatarColor": "#0891B2",
  "departement": "DPT_TRANSPORT"
 },
 {
  "id": "p_49",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "chef.de.departement.projets.distribution@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DER",
  "poste": "Chef de Département Projets Distribution",
  "initials": "KC",
  "avatarColor": "#0F766E",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_50",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "secretaire.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "DER",
  "poste": "Secrétaire / DPD",
  "initials": "MS",
  "avatarColor": "#8B5CF6",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_51",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "controleur.service.controle.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR_TRAVAUX",
  "direction": "DER",
  "poste": "Contrôleur / Service Contrôle DPD",
  "initials": "BK",
  "avatarColor": "#EA580C",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_52",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "chef.de.projet.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DER",
  "poste": "Chef de Projet / DPD",
  "initials": "SM",
  "avatarColor": "#1D4ED8",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_53",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "ingenieur.d.etudes.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DER",
  "poste": "Ingénieur d'Études / DPD",
  "initials": "NT",
  "avatarColor": "#2563EB",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_54",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "assistant.projet.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DER",
  "poste": "Assistant Projet / DPD",
  "initials": "AS",
  "avatarColor": "#4B5563",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_55",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "cartographe.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DER",
  "poste": "Cartographe / DPD",
  "initials": "CF",
  "avatarColor": "#2563EB",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_56",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "assistant.administratif.budget.uagl.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DER",
  "poste": "Assistant Administratif Budget / UAGL DPD",
  "initials": "PG",
  "avatarColor": "#B45309",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_57",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "chauffeur.uagl.dpd@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "DER",
  "poste": "Chauffeur / UAGL DPD",
  "initials": "SW",
  "avatarColor": "#0891B2",
  "departement": "DPD_DISTRIBUTION"
 },
 {
  "id": "p_58",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "directeur.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DGC",
  "poste": "Directeur DGC",
  "initials": "BD",
  "avatarColor": "#0F766E"
 },
 {
  "id": "p_59",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "expert.suivi.evaluation.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DGC",
  "poste": "Expert Suivi-Évaluation DGC",
  "initials": "RN",
  "avatarColor": "#059669"
 },
 {
  "id": "p_60",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "assistante.de.direction.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DGC",
  "poste": "Assistante de Direction / DGC",
  "initials": "AB",
  "avatarColor": "#4B5563"
 },
 {
  "id": "p_61",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "chef.uagl.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "RESP_LOG",
  "direction": "DGC",
  "poste": "Chef UAGL / DGC",
  "initials": "FS",
  "avatarColor": "#0E7490"
 },
 {
  "id": "p_62",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "assistant.administratif.logistique.uagl.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DGC",
  "poste": "Assistant Administratif Logistique / UAGL DGC",
  "initials": "OD",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_63",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "assistant.comptable.uagl.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DGC",
  "poste": "Assistant Comptable / UAGL DGC",
  "initials": "AN",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_64",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "chauffeur.uagl.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "DGC",
  "poste": "Chauffeur / UAGL DGC",
  "initials": "MF",
  "avatarColor": "#0891B2"
 },
 {
  "id": "p_65",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "secretaire.det.gi@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "DGC",
  "poste": "Secrétaire / DET&GI",
  "initials": "MS",
  "avatarColor": "#8B5CF6",
  "departement": "DGC_ETUDES"
 },
 {
  "id": "p_66",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "expert.sig@dpe.sn",
  "password": "dpe2026",
  "role": "SIG",
  "direction": "DGC",
  "poste": "Expert SIG",
  "initials": "CS",
  "avatarColor": "#0D9488",
  "departement": "SIG"
 },
 {
  "id": "p_67",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "geomaticien.sig@dpe.sn",
  "password": "dpe2026",
  "role": "SIG",
  "direction": "DGC",
  "poste": "Géomaticien / SIG",
  "initials": "AG",
  "avatarColor": "#0D9488",
  "departement": "SIG"
 },
 {
  "id": "p_68",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "chef.de.service.immobilisations@dpe.sn",
  "password": "dpe2026",
  "role": "IMMO",
  "direction": "DGC",
  "poste": "Chef de Service Immobilisations",
  "initials": "ID",
  "avatarColor": "#92400E",
  "departement": "IMMO"
 },
 {
  "id": "p_69",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "chef.de.groupe.etudes.immobilisations@dpe.sn",
  "password": "dpe2026",
  "role": "IMMO",
  "direction": "DGC",
  "poste": "Chef de Groupe Études / Immobilisations",
  "initials": "KC",
  "avatarColor": "#92400E",
  "departement": "IMMO"
 },
 {
  "id": "p_70",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "chef.de.groupe.immobilisations@dpe.sn",
  "password": "dpe2026",
  "role": "IMMO",
  "direction": "DGC",
  "poste": "Chef de Groupe Immobilisations",
  "initials": "MS",
  "avatarColor": "#92400E",
  "departement": "IMMO"
 },
 {
  "id": "p_71",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "assistant.immobilisations@dpe.sn",
  "password": "dpe2026",
  "role": "IMMO",
  "direction": "DGC",
  "poste": "Assistant / Immobilisations",
  "initials": "BK",
  "avatarColor": "#92400E",
  "departement": "IMMO"
 },
 {
  "id": "p_72",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "agent.technique.immobilisations@dpe.sn",
  "password": "dpe2026",
  "role": "IMMO",
  "direction": "DGC",
  "poste": "Agent Technique / Immobilisations",
  "initials": "SM",
  "avatarColor": "#92400E",
  "departement": "IMMO"
 },
 {
  "id": "p_73",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "archiviste.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "DGC",
  "poste": "Archiviste / DGC",
  "initials": "NT",
  "avatarColor": "#8B5CF6",
  "departement": "DGC_ETUDES"
 },
 {
  "id": "p_74",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "aide.archiviste.dgc@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "DGC",
  "poste": "Aide-Archiviste / DGC",
  "initials": "AS",
  "avatarColor": "#8B5CF6",
  "departement": "DGC_ETUDES"
 },
 {
  "id": "p_75",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "chef.de.departement.projets.investissement@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DGC",
  "poste": "Chef de Département Projets Investissement",
  "initials": "CF",
  "avatarColor": "#0F766E",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_76",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "secretaire.dpi@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "DGC",
  "poste": "Secrétaire / DPI",
  "initials": "PG",
  "avatarColor": "#8B5CF6",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_77",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "chef.de.projet.dpi@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DGC",
  "poste": "Chef de Projet / DPI",
  "initials": "SW",
  "avatarColor": "#1D4ED8",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_78",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "controleur.dpi@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR",
  "direction": "DGC",
  "poste": "Contrôleur / DPI",
  "initials": "BD",
  "avatarColor": "#D97706",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_79",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "chef.unite.architecture.dessin@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DGC",
  "poste": "Chef Unité Architecture & Dessin",
  "initials": "RN",
  "avatarColor": "#2563EB",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_80",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "dessinateur.principal.dpi@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DGC",
  "poste": "Dessinateur Principal / DPI",
  "initials": "AB",
  "avatarColor": "#2563EB",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_81",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "dessinateur.moyen.dpi@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DGC",
  "poste": "Dessinateur Moyen / DPI",
  "initials": "FS",
  "avatarColor": "#2563EB",
  "departement": "DGC_INVEST"
 },
 {
  "id": "p_82",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "directeur.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DIT",
  "poste": "Directeur DIT",
  "initials": "OD",
  "avatarColor": "#0F766E"
 },
 {
  "id": "p_83",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "expert.suivi.evaluation.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DIT",
  "poste": "Expert Suivi-Évaluation DIT",
  "initials": "AN",
  "avatarColor": "#059669"
 },
 {
  "id": "p_84",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "expert.transition.energetique.dit@dpe.sn",
  "password": "dpe2026",
  "role": "EXPERT",
  "direction": "DIT",
  "poste": "Expert Transition Énergétique / DIT",
  "initials": "MF",
  "avatarColor": "#7C3AED"
 },
 {
  "id": "p_85",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "expert.environnement.social.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "DIT",
  "poste": "Expert Environnement Social / DIT",
  "initials": "MS",
  "avatarColor": "#059669"
 },
 {
  "id": "p_86",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "assistante.de.direction.dit@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "DIT",
  "poste": "Assistante de Direction / DIT",
  "initials": "CS",
  "avatarColor": "#4B5563"
 },
 {
  "id": "p_87",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "chef.uagl.dit@dpe.sn",
  "password": "dpe2026",
  "role": "RESP_LOG",
  "direction": "DIT",
  "poste": "Chef UAGL / DIT",
  "initials": "AG",
  "avatarColor": "#0E7490"
 },
 {
  "id": "p_88",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "assistant.comptable.uagl.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "DIT",
  "poste": "Assistant Comptable / UAGL DIT",
  "initials": "ID",
  "avatarColor": "#B45309"
 },
 {
  "id": "p_89",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "chauffeur.uagl.dit@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "DIT",
  "poste": "Chauffeur / UAGL DIT",
  "initials": "KC",
  "avatarColor": "#0891B2"
 },
 {
  "id": "p_90",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "chef.de.departement.smartgrid.stockage@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DIT",
  "poste": "Chef de Département Smartgrid & Stockage",
  "initials": "MS",
  "avatarColor": "#0F766E",
  "departement": "DIT_SMARTGRID"
 },
 {
  "id": "p_91",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "chef.de.projet.smartgrid@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DIT",
  "poste": "Chef de Projet / Smartgrid",
  "initials": "BK",
  "avatarColor": "#1D4ED8",
  "departement": "DIT_SMARTGRID"
 },
 {
  "id": "p_92",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "chef.de.departement.projets.commercial@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "DIT",
  "poste": "Chef de Département Projets Commercial",
  "initials": "SM",
  "avatarColor": "#0F766E",
  "departement": "DIT_COMMERCIAL"
 },
 {
  "id": "p_93",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "chef.de.projet.commercial@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "DIT",
  "poste": "Chef de Projet / Commercial",
  "initials": "NT",
  "avatarColor": "#1D4ED8",
  "departement": "DIT_COMMERCIAL"
 },
 {
  "id": "p_94",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "ingenieur.projet.commercial@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "DIT",
  "poste": "Ingénieur Projet / Commercial",
  "initials": "AS",
  "avatarColor": "#2563EB",
  "departement": "DIT_COMMERCIAL"
 },
 {
  "id": "p_95",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "coordonnateur.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "CPBM_UE",
  "poste": "Coordonnateur CPBM-UE",
  "initials": "CF",
  "avatarColor": "#0F766E",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_96",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "conseiller.technique.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "EXPERT",
  "direction": "CPBM_UE",
  "poste": "Conseiller Technique CPBM-UE",
  "initials": "PG",
  "avatarColor": "#7C3AED",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_97",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "responsable.audit.interne.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "AUDIT",
  "direction": "CPBM_UE",
  "poste": "Responsable Audit Interne CPBM-UE",
  "initials": "SW",
  "avatarColor": "#475569",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_98",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "responsable.suivi.evaluation.cpbm.ue.2@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPBM_UE",
  "poste": "Responsable Suivi-Évaluation CPBM-UE",
  "initials": "BD",
  "avatarColor": "#059669",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_99",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "responsable.gestion.administrative.financiere.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CPBM_UE",
  "poste": "Responsable Gestion Administrative & Financière CPBM-UE",
  "initials": "RN",
  "avatarColor": "#B45309",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_100",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "responsable.passation.des.marches.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "MARCHES",
  "direction": "CPBM_UE",
  "poste": "Responsable Passation des Marchés CPBM-UE",
  "initials": "AB",
  "avatarColor": "#9333EA",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_101",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "responsable.communication.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPBM_UE",
  "poste": "Responsable Communication CPBM-UE",
  "initials": "FS",
  "avatarColor": "#059669",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_102",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "chauffeur.cpbm.ue@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "CPBM_UE",
  "poste": "Chauffeur CPBM-UE",
  "initials": "OD",
  "avatarColor": "#0891B2",
  "cellule": "CPBM_UE"
 },
 {
  "id": "p_103",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "coordonnateur.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "CC26",
  "poste": "Coordonnateur CC26",
  "initials": "AN",
  "avatarColor": "#0F766E",
  "cellule": "CC26"
 },
 {
  "id": "p_104",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "assistant.coordonnateur.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "CC26",
  "poste": "Assistant Coordonnateur CC26",
  "initials": "MF",
  "avatarColor": "#4B5563",
  "cellule": "CC26"
 },
 {
  "id": "p_105",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "assistante.projets.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "ASSISTANT",
  "direction": "CC26",
  "poste": "Assistante Projets CC26",
  "initials": "MS",
  "avatarColor": "#4B5563",
  "cellule": "CC26"
 },
 {
  "id": "p_106",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "assistant.administratif.comptable.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CC26",
  "poste": "Assistant Administratif & Comptable CC26",
  "initials": "CS",
  "avatarColor": "#B45309",
  "cellule": "CC26"
 },
 {
  "id": "p_107",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "responsable.suivi.evaluation.cc26.2@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CC26",
  "poste": "Responsable Suivi-Évaluation CC26",
  "initials": "AG",
  "avatarColor": "#059669",
  "cellule": "CC26"
 },
 {
  "id": "p_108",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "responsable.genre.inclusion.sociale.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CC26",
  "poste": "Responsable Genre & Inclusion Sociale CC26",
  "initials": "ID",
  "avatarColor": "#059669",
  "cellule": "CC26"
 },
 {
  "id": "p_109",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "responsable.performance.environnementale.sociale.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CC26",
  "poste": "Responsable Performance Environnementale & Sociale CC26",
  "initials": "KC",
  "avatarColor": "#059669",
  "cellule": "CC26"
 },
 {
  "id": "p_110",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "responsable.communication.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CC26",
  "poste": "Responsable Communication CC26",
  "initials": "MS",
  "avatarColor": "#059669",
  "cellule": "CC26"
 },
 {
  "id": "p_111",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "cartographe.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "CC26",
  "poste": "Cartographe CC26",
  "initials": "BK",
  "avatarColor": "#2563EB",
  "cellule": "CC26"
 },
 {
  "id": "p_112",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "chef.de.projet.acces.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "CC26",
  "poste": "Chef de Projet Accès CC26",
  "initials": "SM",
  "avatarColor": "#1D4ED8",
  "cellule": "CC26"
 },
 {
  "id": "p_113",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "ingenieur.travaux.acces.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "CC26",
  "poste": "Ingénieur Travaux Accès CC26",
  "initials": "NT",
  "avatarColor": "#2563EB",
  "cellule": "CC26"
 },
 {
  "id": "p_114",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "chef.de.projet.transport.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "CC26",
  "poste": "Chef de Projet Transport CC26",
  "initials": "AS",
  "avatarColor": "#1D4ED8",
  "cellule": "CC26"
 },
 {
  "id": "p_115",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "ingenieur.travaux.transport.cc26@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "CC26",
  "poste": "Ingénieur Travaux Transport CC26",
  "initials": "CF",
  "avatarColor": "#2563EB",
  "cellule": "CC26"
 },
 {
  "id": "p_116",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "chef.de.cellule.cpamacel.ee@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "CPAMACEL_EE",
  "poste": "Chef de Cellule CPAMACEL & EE",
  "initials": "PG",
  "avatarColor": "#0F766E",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_117",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "responsable.administratif.financier.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CPAMACEL_EE",
  "poste": "Responsable Administratif & Financier CPAMACEL",
  "initials": "SW",
  "avatarColor": "#B45309",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_118",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "comptable.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CPAMACEL_EE",
  "poste": "Comptable CPAMACEL",
  "initials": "BD",
  "avatarColor": "#B45309",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_119",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "secretaire.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "CPAMACEL_EE",
  "poste": "Secrétaire CPAMACEL",
  "initials": "RN",
  "avatarColor": "#8B5CF6",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_120",
  "prenom": "Amadou",
  "nom": "BA",
  "email": "chauffeur.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "CPAMACEL_EE",
  "poste": "Chauffeur CPAMACEL",
  "initials": "AB",
  "avatarColor": "#0891B2",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_121",
  "prenom": "Fatou",
  "nom": "SOW",
  "email": "chef.de.projet.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "CPAMACEL_EE",
  "poste": "Chef de Projet CPAMACEL",
  "initials": "FS",
  "avatarColor": "#1D4ED8",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_122",
  "prenom": "Ousmane",
  "nom": "DIOP",
  "email": "expert.passation.marches.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "MARCHES",
  "direction": "CPAMACEL_EE",
  "poste": "Expert Passation Marchés CPAMACEL",
  "initials": "OD",
  "avatarColor": "#9333EA",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_123",
  "prenom": "Aïssatou",
  "nom": "NDIAYE",
  "email": "expert.suivi.evaluation.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPAMACEL_EE",
  "poste": "Expert Suivi-Évaluation CPAMACEL",
  "initials": "AN",
  "avatarColor": "#059669",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_124",
  "prenom": "Modou",
  "nom": "FALL",
  "email": "expert.environnement.social.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPAMACEL_EE",
  "poste": "Expert Environnement Social CPAMACEL",
  "initials": "MF",
  "avatarColor": "#059669",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_125",
  "prenom": "Mariama",
  "nom": "SECK",
  "email": "expert.technique.cpamacel@dpe.sn",
  "password": "dpe2026",
  "role": "INGENIEUR",
  "direction": "CPAMACEL_EE",
  "poste": "Expert Technique CPAMACEL",
  "initials": "MS",
  "avatarColor": "#2563EB",
  "cellule": "CPAMACEL_EE"
 },
 {
  "id": "p_126",
  "prenom": "Cheikh",
  "nom": "SARR",
  "email": "chef.de.cellule.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_DEPT",
  "direction": "CPADERAU",
  "poste": "Chef de Cellule CPADERAU",
  "initials": "CS",
  "avatarColor": "#0F766E",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_127",
  "prenom": "Awa",
  "nom": "GUEYE",
  "email": "responsable.administratif.financier.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CPADERAU",
  "poste": "Responsable Administratif & Financier CPADERAU",
  "initials": "AG",
  "avatarColor": "#B45309",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_128",
  "prenom": "Ibrahima",
  "nom": "DIALLO",
  "email": "comptable.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CTRL_FIN",
  "direction": "CPADERAU",
  "poste": "Comptable CPADERAU",
  "initials": "ID",
  "avatarColor": "#B45309",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_129",
  "prenom": "Khady",
  "nom": "CISSE",
  "email": "secretaire.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "SECRETAIRE",
  "direction": "CPADERAU",
  "poste": "Secrétaire CPADERAU",
  "initials": "KC",
  "avatarColor": "#8B5CF6",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_130",
  "prenom": "Moussa",
  "nom": "SY",
  "email": "responsable.communication.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Responsable Communication CPADERAU",
  "initials": "MS",
  "avatarColor": "#059669",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_131",
  "prenom": "Bineta",
  "nom": "KANE",
  "email": "responsable.suivi.environnemental.social.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Responsable Suivi Environnemental & Social CPADERAU",
  "initials": "BK",
  "avatarColor": "#059669",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_132",
  "prenom": "Serigne",
  "nom": "MBAYE",
  "email": "expert.hse.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Expert HSE CPADERAU",
  "initials": "SM",
  "avatarColor": "#059669",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_133",
  "prenom": "Ndeye",
  "nom": "THIAM",
  "email": "expert.social.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Expert Social CPADERAU",
  "initials": "NT",
  "avatarColor": "#059669",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_134",
  "prenom": "Aliou",
  "nom": "SANE",
  "email": "expert.passation.marches.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "MARCHES",
  "direction": "CPADERAU",
  "poste": "Expert Passation Marchés CPADERAU",
  "initials": "AS",
  "avatarColor": "#9333EA",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_135",
  "prenom": "Coumba",
  "nom": "FAYE",
  "email": "expert.suivi.evaluation.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHARGE",
  "direction": "CPADERAU",
  "poste": "Expert Suivi-Évaluation CPADERAU",
  "initials": "CF",
  "avatarColor": "#059669",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_136",
  "prenom": "Pape",
  "nom": "GNINGUE",
  "email": "chef.de.projet.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "CPADERAU",
  "poste": "Chef de Projet CPADERAU",
  "initials": "PG",
  "avatarColor": "#1D4ED8",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_137",
  "prenom": "Sokhna",
  "nom": "WADE",
  "email": "controleur.genie.civil.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CONTROLEUR_TRAVAUX",
  "direction": "CPADERAU",
  "poste": "Contrôleur Génie Civil CPADERAU",
  "initials": "SW",
  "avatarColor": "#EA580C",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_138",
  "prenom": "Babacar",
  "nom": "DIENG",
  "email": "chef.de.projet.reseaux.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHEF_PROJ",
  "direction": "CPADERAU",
  "poste": "Chef de Projet Réseaux CPADERAU",
  "initials": "BD",
  "avatarColor": "#1D4ED8",
  "cellule": "CPADERAU"
 },
 {
  "id": "p_139",
  "prenom": "Rokhaya",
  "nom": "NIANG",
  "email": "chauffeur.cpaderau@dpe.sn",
  "password": "dpe2026",
  "role": "CHAUFFEUR",
  "direction": "CPADERAU",
  "poste": "Chauffeur CPADERAU",
  "initials": "RN",
  "avatarColor": "#0891B2",
  "cellule": "CPADERAU"
 }
];
