/**
 * referentielsDPE.ts — Nomenclatures OFFICIELLES SENELEC/DPE.
 * Source : « Modèle Type structuration des projets » (feuille « Liste de valeurs »).
 * Sert de source unique pour : Immobilisations (classe comptable + actif livrable + unité),
 * Marchés/BOQ (type de dépense, bailleur), structuration projet (WBS/RACI).
 */

/** Classe comptable d'immobilisation (NATURE — plan comptable SYSCOHADA, classe 2). */
export const IMMO_CLASSES: string[] = [
  "511",
  "512",
  "513",
  "514",
  "515",
  "516",
  "517",
  "521",
  "522",
  "523",
  "524",
  "525",
  "526",
  "527",
  "531",
  "532",
  "533",
  "534",
  "535",
  "536",
  "537",
  "541",
  "542",
  "560",
  "510",
  "518",
  "519",
  "520",
  "528",
  "529",
  "530",
  "538",
  "539",
  "540",
  "561",
  "562",
  "800",
  "801",
  "802",
  "545",
  "547",
  "549",
  "544",
];

/** Bailleurs / sources de financement. */
export const BAILLEURS: string[] = [
  "AFD(2011)",
  "AFD(2018)",
  "AR",
  "AR(BID)",
  "AR(BM)",
  "AR(EIFFAGE)",
  "AR(KFW (85%))",
  "AR(KIAT)",
  "AR(VINCI)",
  "AR(WAPP)",
  "BAD",
  "BCI-ETAT",
  "BID",
  "BM(PASE1)",
  "BM(PASE2)",
  "BOAD(25Mds)",
  "BOAD(FDE)",
  "Contrepartie Annulation dette Espagnole",
  "CORIS+CDS",
  "EIFFAGE",
  "EMPRUNT OBLIGATAIRE",
  "ETAT SENEGAL",
  "EU(PASE2)",
  "EXIM BANK CHINE",
  "FE (retenuede garantie SUNIR)",
  "FONDS PREFERENCE",
  "FONDS PROPRES",
  "FSE",
  "IPP",
  "JICA (DON)",
  "KALPATARU 1",
  "KALPATARU 2",
  "KFW (70%)",
  "KFW (85%)",
  "MCC",
  "OMVG",
  "OMVS",
  "SAPCO",
  "BNP PARIBAS",
  "WELDY LAMONT (EXIMBANK US)",
  "AR (BL)",
  "AR(BEI)",
  "BANQUE MONDIALE",
  "BANQUES LOCALES",
  "BEI",
  "KFW",
  "KIAT",
  "MATELEC",
  "VINCI",
  "AR(ETAT SENEGAL)",
  "AR(ECOBANK)",
  "AR(PASE2-BEI/UE)",
];

/** Actif livrable (composant produit par le projet → futur immobilisé). */
export const ACTIFS_LIVRABLES: string[] = [
  "Alternateur avec Régulateur de tension",
  "Antenne radio",
  "Armoires et Tableaux BT",
  "Ascenseur",
  "Ascenseur de charge",
  "Autocommutateur",
  "Autre",
  "Autres Equipements divers",
  "Autres Travaux divers",
  "Batiment Usage Industriel",
  "Batiment Usage Commercial",
  "Batiment Usage Bureau",
  "Baie Stockage",
  "Banc de Condensateurs",
  "Base de données",
  "Batterie de Stockage",
  "Branchement BT aérien",
  "Branchement BT souterrain",
  "Cabine Mobile HTA/BT AIS",
  "Cabine Mobile HTA/BT GIS",
  "Réseau Fibre Optique",
  "Cable Pilote Fibre Optique",
  "Cable pilote fibre optique",
  "Cable souterrain BT",
  "Cable souterrain HTA",
  "Cable souterrain HTB",
  "Cable sous marin HTB",
  "Câbles et Chemins de câble",
  "Canalisation souterraine HTB",
  "Carrelage",
  "Chaine Isolateur et Accessoires",
  "Chaudière",
  "Circuit de récupération de chaleur",
  "Circuits des auxiliaires mécaniques",
  "Commun des tranches centrale",
  "Commun des travées poste HTB",
  "Compteur Commercial Classique",
  "Compteur Commercial Communicant",
  "Compteur Commercial Prépaiement",
  "Conducteur et Cable de garde",
  "Couloir ligne de Transport",
  "Désaffectation actif",
  "Electricité",
  "Elévation Mur et Toiture",
  "Enregistreur Réseau",
  "Equipement de SCADA",
  "Equipement de Télécoms",
  "Equipement de Téléconduite",
  "Equipement Electrique Poste HTA/BT H59 Cellule fermée AIS",
  "Equipement Electrique Poste HTA/BT H59 Cellule fermée GIS",
  "Equipement Electrique Poste HTA/BT H59 Cellule ouverte",
  "Equipement Electrique Poste HTA/BT H61",
  "Equipement Electrique Sous-Station HTA/HTA",
  "Equipement Electrique Sous-Station HTA/HTA Cellule fermée AIS",
  "Equipement Electrique Sous-Station HTA/HTA Cellule fermée GIS",
  "Equipement Electrique Sous-Station HTA/HTA Cellule ouverte",
  "Equipement Informatique",
  "Equipement Moteur",
  "Etudes de Faisabilité",
  "Etudes d'Exécution",
  "Etudes d'Impact Environnemental et Social",
  "Firewall",
  "Formation",
  "Frais d’acquisition des Permis",
  "Frais d'Acquisition Terrain",
  "Génie Civil Poste HTA/BT",
  "Génie Civil Sous-Station HTA/HTA",
  "GPS",
  "Groupe Electrogène de Secours",
  "Huisserie industrielle Porte et Fenêtre",
  "Imprimante Personnel",
  "Imprimante Réseau",
  "Inductance",
  "Infrastructure Informatique",
  "Installation intérieure BT",
  "Inspection et Contrôle",
  "Ligne aérienne HTA",
  "Ligne souterraine HTA",
  "Ligne sous marine HTA",
  "Logiciel",
  "Logiciel Applicatif",
  "Marketing",
  "Mobilier de Bureau",
  "Matériel roulant",
  "Matériel de Sécurité Electrique",
  "Matériel de Sécurité Incendie",
  "Menuiserie",
  "Modem 4G",
  "Onduleur Basse Tension",
  "Onduleur Chargeur Production Photovoltaïque",
  "Onduleur Réseau Production Photovoltaïque",
  "Outillage",
  "Panneaux Solaires Champ Photovoltaïque",
  "Peinture",
  "Pièces de Rechange",
  "Plan d'Action de Réinstallation",
  "Plan de Gestion Environnementale et Sociale",
  "Plateforme logicielle",
  "Plomberie",
  "Pont roulant et Palan",
  "Poste de Travail",
  "Poste de Travail Bureau",
  "Poste de Travail Client Léger",
  "Poste de Travail Portable",
  "Poste de Travail Tablette",
  "Poste Préfabriqué HTA/BT AIS",
  "Poste Préfabriqué HTA/BT GIS",
  "Pylône et Massif",
  "Pylône et Massif de remontée",
  "Pylone radio",
  "Reclassement commercial",
  "Régulateur Basse Tension",
  "Régulateur de charge Production Photovoltaique",
  "Réseau Basse Tension Aérien",
  "Réseau Basse Tension Souterrain",
  "Réseau Informatique",
  "Routeur",
  "Scanner",
  "Serveur",
  "Service après comptage commercial",
  "Services Auxiliaires Basse Tension",
  "Structure béton armé et Canalisation",
  "Structure métallique",
  "Support Interconnexion LAN ET MAN",
  "Switch",
  "Système de Détection Incendie",
  "Système de Mise à la Terre Poste",
  "Système de Protection et de Contrôle Commande",
  "Système de Téléconduite et Télécoms",
  "Système Eclairage",
  "Système Protection Foudre",
  "Système stockage combustible",
  "Système de contrôle d'accès",
  "Tableau HTA Centrale",
  "Tableau HTA Primaire Poste Source",
  "Tableau HTA Secondaire Poste Source",
  "Téléphone Analogique",
  "Téléphone IP",
  "Transformateur Auxiliaire",
  "Transformateur de Puissance",
  "Transformateur Eleveur de puissance",
  "Travée Couplage Barres",
  "Travée Ligne",
  "Travée Sectionnement Barres",
  "Travée Transformateur Potentiel",
  "Travée Transformateur Puissance",
  "Travée Tronçonnement Barres",
  "Travée Inductance",
  "Ventilation et Air conditionné",
  "Ventilation industrielle du bâtiment",
  "Vidéosurveillance",
  "Voierie",
];

/** Unité de l'actif livrable. */
export const UNITES_ACTIF: string[] = [
  "ML",
  "MVA",
  "MVAR",
  "M2",
  "M3",
  "MW",
  "HA",
  "KG",
  "JOURS",
  "MOIS",
  "HOMME MOIS",
  "U",
];

/** Type de dépense (ventilation budgétaire / décompte). */
export const TYPES_DEPENSE: string[] = [
  "Services EIES/PGES/PAR-Hors Domaine",
  "Services de Passation Marché-Hors Domaine",
  "Services de Système Information-Hors Domaine",
  "Services de Génie Civil-Hors Domaine",
  "Achats et Sorties Magasin du Domaine",
  "Frais de Personnel Cadre-Domaine",
  "Frais de Personnel Maîtrise-Domaine",
  "Frais de Personnel Ouvriers-Domaine",
  "Véhicule de Transport Matériel du Domaine",
  "Véhicule de Transport Personnel du Domaine",
  "Frais de Déplacement du Domaine",
  "Frais des études et de contrôle du Projet",
  "Engin Special du Domaine",
  "Charge Support Exécution du Projet",
  "Taxes sur Valeur Ajoutée",
  "Taxe au Cordon Douanier",
  "Contrat T/F/SE sur Fonds Propres",
  "Contrat T/F/SE sur Dettes directes",
  "Contrat T/F/SE sur Rétrocession Dette Etat",
  "Contrat T/F/SE sur Fonds de Préférence",
  "Contrat T/F/SE sur Fonds Soutien Energie",
  "Contrat T/F/SE sur Subvention Etat",
  "Contrat T/F/SE sur Don",
  "Contrat T/F/SE sur Financement Tiers",
  "Contrat T/F/SE sur Financement IPP",
  "Contrat T/F/SE sur Financement CER",
];

/** Composantes de coût d'un BOQ (Bordereau des Quantités) — modèle DPE. */
export const BOQ_COMPOSANTES = ['Fourniture', 'Transport', 'Travaux'] as const;
export type BoqComposante = typeof BOQ_COMPOSANTES[number];
